spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: hee01312020
    url: jdbc:mariadb://localhost:3306/concert
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
  redis:
    host: localhost
    port: 6379
    password: hee01312020

#
#logging:
#  level:
#    org.apache.kafka: debug
