spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: test1234
    url: jdbc:mariadb://localhost:3306
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
